/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   authorization-selector.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {AuthorizationSelector} from './src/AuthorizationSelector.js';

export {AuthorizationSelector};
